# see http://about.travis-ci.org/docs/user/languages/php/ for more hints

language: php
php:
  - '5.6'
  - '7.1'
  - hhvm # on Trusty only
  - nightly

# configure notifications (email, IRC, campfire etc)
notifications:
  email:
    recipients:
      - michael@longanime.com.br
    on_success: never # default: change
    on_failure: always # default: always